### ISSUE TITLE
Issues when mount plex server directories on windows

### ISSUE THREAD

**Issue by Cologler** [johnkiddjr/PlexMatch-File-Generator#16]
My Plex server was hosted on a Linux NAS, and the device was mounted on windows volume. when I try to use PlexMatch-File-Generator, it is unable to parse root path like `--root V:\video:/volume2/video`.

It was nice if this support more than one `--root` argument.

**Comment by johnkiddjr** [comment]
Can you attach a log file so I can see exactly where the issue is?

Enable logging output to file with the `-l path/to/log` switch

**Comment by Cologler** [comment]
when root args `V:\video:/volume2/video` split with `:`, it split into 3 parts.

**Comment by curtisbarnard** [comment]
I seem to be having a problem with this as well. The parser seems to be working, but the folders aren't being found. I can look in explorer and see that these folders are on the `X:\` drive. Here's the command output when I run it with `-r X:\:/tv/` :

```
[18:25:03 ERR] Missing or Invalid Folder: X:\Friends
[18:25:03 ERR] Missing or Invalid Folder: X:\Home Improvement
[18:25:04 ERR] Missing or Invalid Folder: X:\New Girl
[18:25:04 ERR] Missing or Invalid Folder: X:\The Office (2005)
[18:25:04 ERR] Missing or Invalid Folder: X:\This Old House (1979) {tmdb-2394}
[18:25:04 INF] Processed results for TV Shows: 5 processed
[18:25:04 INF] Operation Completed
```

**Comment by johnkiddjr** [comment]
@curtisbarnard The X drive is mounted on your local computer, the one running the application correct? And those folders exist? My test environment has a similar structure to it and I'm not seeing an issue. I thought the cause might be the ```\``` but even when I use that it still works for me.

**Comment by johnkiddjr** [comment]
@curtisbarnard  Can you open PowerShell, change to your X: drive (just type ```x:``` and press enter to do so), then paste the output of running ```Get-ChildItem``` on the root of the drive for me?
