### ISSUE TITLE
Tool does not generate site IDs

### ISSUE THREAD

**Issue by Soitora** [johnkiddjr/PlexMatch-File-Generator#30]
Hey

Adding some way of generating site IDs would be nice
Or at the very least, don't have it override my already existing files which has ID in them

Fortunately for me, I only had one series set with manual ID, so nothing much was lost

https://support.plex.tv/articles/plexmatch/
It can set `tmdbid`, `tvdbid`, and `imdbid`
So either if a way to generate these was found, or at least a way to keep those lines safe

**Comment by johnkiddjr** [comment]
I'll look into adding those id's to the match data, and adding a flag to disable overwriting.

From my understanding though, the Plex Guid should provide a better match than the site id's do.

**Comment by johnkiddjr** [comment]
@Soitora
Sorry this took so long for me to look into, but I don't see these ID's in the data returned by the Plex server. I will be adding a command switch to disable automatic overwrite though.
