### ISSUE TITLE
Getting an ERR on every single folder Missing or Invalid Folder:

### ISSUE THREAD

**Issue by christoney** [johnkiddjr/PlexMatch-File-Generator#46]
Hi JohnKiddjr, hope you have seen this issue before and I'm just not seeing it.  Problem with ERR on each item. Running command in the user/Downloads folder. Logs to folder in same.  

Microsoft Windows [Version 10.0.22631.2715]
PlexMatchGenerator Version: 0.9.2-rc2

Using this command with a:
PlexMatchGenerator-Windows-x86.exe --url http://192.168.#.##:32400 --token xxxxxxxxxxx -r /DS920PLUS/MyMedia:/volume2/MyMedia -l C:\Users\vip95\Downloads\Logs -lib "TV Shows" -lib "Movies"

Resulting in all folders getting the below:
16:01:52 ERR] Missing or Invalid Folder: /DS920PLUS/MyMedia/Movies/Young Frankenstein (1974)
[16:01:52 INF] Processed results for Movies: 250 processed
[16:01:52 ERR] Missing or Invalid Folder: /DS920PLUS/MyMedia/TV/1883 (2021)
[16:01:55 INF] Processed results for TV Shows: 252 processed
[16:01:55 INF] Library Audiobooks skipped because it is not in the list of libraries to process
[16:01:55 INF] Library Chris-Music skipped because it is not in the list of libraries to process
[16:01:55 INF] Library Home Videos skipped because it is not in the list of libraries to process
[16:01:55 INF] Operation Completed

I've checked the existing folders but no new .plexmatch file. Am I overlooking something?

**Comment by johnkiddjr** [comment]
Looks like you're on Windows, but the path provided to the -r command isn't a valid Windows path:

/DS920PLUS/MyMedia <- This is the local path, but this is not a valid Windows Path. 
/volume2/MyMedia <- This is the path local to your plex server

Assuming DS920PLUS is a file server of some kind that is accessed via hostname, the correct path should be: \\DS920PLUS\MyMedia

**Comment by christoney** [comment]
Thanks for the quick response, tried this command with the backslash instead of forward slashes, but same error: PlexMatchGenerator-Windows-x86.exe --url http://192.168.#.##32400 --token xxxxxxxxx -r \DS920PLUS\MyMedia:/volume2/MyMedia -l C:\Users\vip95\Downloads\Logs -lib "TV Shows" -lib "Movies". 
And you are correct in that DS920Plus is the server (NAS) where the media files live. /volume2/MyMedia is what Plex uses as Plex is installed on the Synology NAS.

**Comment by christoney** [comment]
This however has worked now. PlexMatchGenerator-Windows-x86.exe --url http://192.168.#.##:32400 --token xxxxxxxxxx -r \\DS920PLUS\MyMedia:/volume2/MyMedia -l C:\Users\vip95\Downloads\Logs -lib "TV Shows" -lib "Movies"
Two backslashes needed for this in windows. As per the usual! I'm checking the output now. Thanks for the extra eyeballs.

**Comment by johnkiddjr** [comment]
You are correct, I forget markdown hates backslashes :)

**Comment by christoney** [comment]
Closing as complete. Windows paths on network get two backslashes!
