### ISSUE TITLE
Imdb and or tmdb numbers added to the .plexmatch

### ISSUE THREAD

**Issue by undeadmky** [johnkiddjr/PlexMatch-File-Generator#47]
Sonarr creates .plexmatch and adds imdb ID and tmdb ID for seasons. So far only your code does .plexmatch for movies. Very thankful for that but any chance of getting the imdb and or tmdb ID added in like sonarr does? I feel plex doesn't recognize all movies and with those codes it can find them easier

**Comment by johnkiddjr** [comment]
This application uses the Plex API to get the media information. The Plex API does not return IMDB, TMDB, TVDB, or any other 3rd party IDs. Sonarr can add that information, because it already has that information.

Plex API: https://www.plexopedia.com/plex-media-server/api/
