### ISSUE TITLE
Unhandled Exception trying to run it on UNRAID

### ISSUE THREAD

**Issue by jedimstr** [johnkiddjr/PlexMatch-File-Generator#5]
Thanks for this tool!
I'm trying to run this on UNRAID and execution seems to work to the point that it prompts for token or runs when I feed it proper params on execution, but then it crashes with:
`Unhandled exception. System.NullReferenceException: Object reference not set to an instance of an object.
   at Program.<Main>$(String[] args)
Aborted
`

**Comment by jedimstr** [comment]
@johnkiddjr the currently released prod latest for UNRAID: version 6.9.2
Also PlexPass enabled server - Version 1.25.9.5673 via the official Plex docker container.

Do you have to be in the actual library path to execute this or does it generate the .plexmatch file through the Plex server itself?

**Comment by johnkiddjr** [comment]
@jedimstr The tool uses the path returned by the Plex server to find your media files, so for *nix servers you'd have to have a share mounted in the same way on the server running the application as your plex server.

For instance, my plex server has the files mounted at /mnt/mediastore so all the filepaths come back as /mnt/mediastore/Library/Show, so if I were running that on a computer other than the Plex server itself, I'd just have to mount my media to /mnt/mediastore and it will run fine.

**Comment by jedimstr** [comment]
@johnkiddjr aaah that would explain the issue then.  I'm trying to run it on the host server's shell, but the docker container for the Plex server has mapped paths for the media libraries passed to it, so internally in the container the path looks different than what it looks like on the host.  Maybe I can try running it on the shell from within the container but that may be limited.

Anyone who runs Plex via a Docker Container (pretty common) will see this issue then.

**Comment by johnkiddjr** [comment]
@jedimstr It likely won't work inside the container, they tend to leave out any normal linux stuff that is needed to run software other than their own.

You could make a symbolic link from where the media is on the host OS to a folder named the same thing as it is in the Plex container:

So if plex sees the media at `/media` but it's mounted at `/mnt/media` you could use this command to create the link:

`ln -s  /mnt/media /media`

**Comment by jedimstr** [comment]
I created a symbolic link and verified I'm able to access all the Libraries using the symbolic link that matches with the internal container path in Plex's settings, but now I get:
`-bash: ./PlexMatchGenerator-Linux-x64: No such file or directory
`

**Comment by jedimstr** [comment]
Getting same error now after making a symbolic link.  Verified that the Soft Link shows the libraries matching the path in the Plex container.

**Comment by johnkiddjr** [comment]
@jedimstr 
I created a new release based on your issues.

It adds better console logging and error handling, the ability to write the log to disk, and an optional parameter to modify the root path for when paths don't match.

Use: `-l /path/for/logfile` to specify the path to save the log file to
Use: `-r /path/on/host:/path/on/plex` to specify differences in root path

Let me know if this fixes all your issues, or at least gives us a better error to work with now

**Comment by johnkiddjr** [comment]
I added better null checking and better error messages to v0.2.2. From what I can see it appears the server was sending back either no response or a bad response so I added messaging to indicate where and what that is.

Do you get this immediately after running, or is there a delay of roughly 30-60 seconds first?

**Comment by jedimstr** [comment]
@johnkiddjr 
Re-ran with v0.2.2 and get this now:
14:38:24 INF] Logger attached. Startup complete. Running file generator...
[14:38:25 ERR] No data or malformed data received from server when querying for libraries
[plexmatch.log](https://github.com/johnkiddjr/PlexMatch-File-Generator/files/8392209/plexmatch.log)

I do specify that SSL is required... hmmm

**Comment by jedimstr** [comment]
I think that was it... SSL.  I had used http:// in the -u param instead of https:// and my Plex server is set to only allow secure connections.  It's currently successfully writing .plexmatch files (still going).

**Comment by johnkiddjr** [comment]
Great, let me know if it completes successfully.

Thanks!

**Comment by jedimstr** [comment]
Completed successfully but took a bit, I've got large libraries.
Surprised by the minimal data in each .plexmatch file. Just titles and GUID's for the most part?
