### ISSUE TITLE
Paging

### ISSUE THREAD

**Issue by ukdtom** [johnkiddjr/PlexMatch-File-Generator#6]
Not tried your fine tool, but looking at the code, it looks like for a library/section you access the /all endpoint

I strongly recommend, that you use paging!

X-Plex-Container-Start and X-Plex-Container-Size

**Comment by johnkiddjr** [comment]
@ukdtom I will look into it! Yesterday was my first day playing around with the Plex APIs so I'm not super familiar yet.

For reference though, the all endpoint returns in under a second for me though, and I have 680 movies and 562 tv shows on there.

**Comment by ukdtom** [comment]
Well, for a large library, you would lock the database until it finished, which is bad, and could lead to a potential PMS crash

**Comment by johnkiddjr** [comment]
Makes sense. I can look into this tonight.

**Comment by ukdtom** [comment]
Use like:

```
VARSTART=0

Loop
https://PMS:32400/library/sections/1/all?X-Plex-Container-Start=VARSTART&X-Plex-Container-Size=50
Do stuff
VARSTART +=50
goto Loop
```
